### PR TITLE
[WIP] Making UpSet an npm module

### PR DESCRIPTION
**Pull request by jeffbaumes**
This does several small things to make UpSet close to a reusable module.
* Creates `package.json`
* Sets up a simple webpack build that does nearly the same as concatenating the files
* Changes CSS rules to not affect all of `<body>` with font
* Adds an optional `datasets` parameter to UpSet initialization that will enable dynamic or inlined data.

To do:
 - [ ] Include an HTML template in the library and a function to fill a div with it
 - [ ] Testing, sanity checking, documentation
 - [ ] Make `updateQueryParameters` an option so if embedded in another app it does not modify the window URL location (currently this logic is commented out)

Note: It seems "upset" is not taken on npm so it could be placed there.

### CODE REVIEW

**Comment by alexsb** [comment]
Thanks Jeff, this is great! I'll test it over the weekend and merge then!

**Comment by jeffbaumes** [comment]
Thanks! Note that your nice permalinking routing is disabled on this PR. I'm ok if you put those back in (a few commented lines that call `updateQueryParameters`). I can probably make this a true option sometime next week.

**Comment by alexsb** [comment]
I merged this - the queryParameters implementation is unfortunately rather buggy anyways, so we're not missing a ton here.

**Comment by jeffbaumes** [comment]
Thanks @alexsb!

**Pull request merged**
